### PR TITLE
Cleans up html and css involving intro.js

### PR DESCRIPTION
**Pull request by jmangel**
Reverts introjs.css to original third-party file, creates introdemo.css for our specific modifications, changes .oversize max-width to 100% and .header min-width to 300px;
Removes header id from introdemo.html, steps.js now finds that element by class and finds the button on the homepage by element (ie. 'button');
Moves the link on the homepage from the first section to the middle section;
Removes stepNumbers and buttons from the introJs objects, and adds progress bar to introDemo;

### CODE REVIEW

**Comment by jmangel** [comment]
This will resolve issues #41 and #43 in the introdemo repo, as well as making the introJs walkthroughs look a little nicer. Please review @amundo or @dwhieb

**Comment by jmangel** [comment]
I just added a second commit that will resolve issues #44, #46, and #47 in introdemo repo

**Comment by amundo** [comment]
This looks great! The `Restart demo` and `Return to homepage` links are useful. Question:

screen shot 2015-05-11 at 4 34 50 pm

Are you getting the same placement of the blurb  for the dictionary set as shown in this screenshot? Wondering if this is something that could be fixed with the `position` attribute on the `#dictionary` step.

**Comment by jmangel** [comment]
@amundo No I'm not getting that problem; what browser is that btw? I just made some css changes that *might* fix that, but I'm not sure because I didn't have that problem to begin with. I'll commit them shortly.

**Pull request merged**
